#!/bin/bash
# Name: mkscript
# Description: Create script
# Author: Lin
# Version: 0.0.1
# Datetime: 2016-07-26 22:42:30
# Usage: mkscript FILENAME
if ! grep "[^[:space:]]" $1 &> /dev/null ;then
cat > $1 << EOF
#!/bin/bash
# Name: `basename $1`
# Description: 
# Author: Lin
# Version: 0.0.1
# Datetime: `date "+%F %T"`
# Usage: `basename $1`

EOF
fi
vim + $1
until bash -n $1 &> /dev/null ;do
        read -p "Syntax Error,q|Q for quiting,others for editing:" OPT 
	        case $OPT in
		q|Q)
			echo "Quit."
			exit 8;; 
		*)  
		        vim + $1
	        esac
done

chmod +x $1

